In [9]:
import torch

x = torch.Tensor([5,3] ) 
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [4]:
x = torch.zeros([2,5])

print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
x.shape

In [6]:
y = torch.rand([2,5])

y

tensor([[0.4176, 0.9421, 0.0245, 0.1174, 0.0493],
        [0.9275, 0.6663, 0.8699, 0.0509, 0.0169]])

In [8]:
y.view([1,10])

tensor([[0.4176, 0.9421, 0.0245, 0.1174, 0.0493, 0.9275, 0.6663, 0.8699, 0.0509,
         0.0169]])