In [5]:
import torch

x = torch.Tensor([5,3]) 
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [6]:
x = torch.zeros([2,5])

print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [7]:
x.shape

torch.Size([2, 5])

In [8]:
y = torch.rand([2,5])

y

tensor([[0.2358, 0.7280, 0.5030, 0.0408, 0.9572],
        [0.1910, 0.7936, 0.7829, 0.4488, 0.2649]])

In [22]:
y.view(10)

tensor([0.2358, 0.7280, 0.5030, 0.0408, 0.9572, 0.1910, 0.7936, 0.7829, 0.4488,
        0.2649])

In [21]:
y.view(1, 10)

tensor([[0.2358, 0.7280, 0.5030, 0.0408, 0.9572, 0.1910, 0.7936, 0.7829, 0.4488,
         0.2649]])

In [20]:
y.view([1, 10])

tensor([[0.2358, 0.7280, 0.5030, 0.0408, 0.9572, 0.1910, 0.7936, 0.7829, 0.4488,
         0.2649]])